version: "3"
services:
  zip_geosearch:
    image: ghcr.io/mahaupt/zip_geosearch:latest
    #build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb://mongo:27017/
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: {}